#!/usr/bin/env python3
"""
Migration script for System Strategies tables
Run this after deploying to add support for:
- System TradingView strategies (admin-created)
- User subscriptions to system strategies
- Outgoing webhooks for signal forwarding
"""
import os
import psycopg2
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv('DATABASE_URL')

def run_migration():
    """Run the system strategies migration"""
    if not DATABASE_URL:
        print("❌ DATABASE_URL environment variable not set")
        return False

    print("=" * 60)
    print("System Strategies Migration")
    print("=" * 60)

    try:
        conn = psycopg2.connect(DATABASE_URL)
        conn.autocommit = True
        cur = conn.cursor()

        # Read and execute the SQL migration file
        migration_file = os.path.join(os.path.dirname(__file__), 'migrations', '002_system_strategies.sql')

        if os.path.exists(migration_file):
            print(f"\n📄 Reading migration file: {migration_file}")
            with open(migration_file, 'r') as f:
                sql = f.read()

            print("🔄 Executing migration...")
            cur.execute(sql)
            print("✅ Migration SQL executed successfully")
        else:
            print(f"⚠️  Migration file not found, running inline migration...")
            # Inline migration as fallback
            run_inline_migration(cur)

        # Verify tables were created
        print("\n📋 Verifying tables...")

        tables_to_check = [
            'system_strategies',
            'user_strategy_subscriptions',
            'user_outgoing_webhooks'
        ]

        for table in tables_to_check:
            cur.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables
                    WHERE table_name = %s
                )
            """, (table,))
            exists = cur.fetchone()[0]
            status = "✅" if exists else "❌"
            print(f"   {status} {table}")

        # Check for new column in user_bot_configs
        cur.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'user_bot_configs' AND column_name = 'system_strategy_id'
            )
        """)
        col_exists = cur.fetchone()[0]
        status = "✅" if col_exists else "❌"
        print(f"   {status} user_bot_configs.system_strategy_id column")

        cur.close()
        conn.close()

        print("\n" + "=" * 60)
        print("✅ Migration completed successfully!")
        print("=" * 60)
        print("\nNext steps:")
        print("1. Create system strategies in Admin panel")
        print("2. Users can now subscribe to system strategies")
        print("3. Configure outgoing webhooks for signal forwarding")

        return True

    except Exception as e:
        print(f"\n❌ Migration failed: {e}")
        return False


def run_inline_migration(cur):
    """Run migration inline if SQL file not found"""

    # System Strategies table
    cur.execute("""
        CREATE TABLE IF NOT EXISTS system_strategies (
            id SERIAL PRIMARY KEY,
            name VARCHAR(100) NOT NULL,
            symbol VARCHAR(20) NOT NULL,
            timeframe VARCHAR(20) NOT NULL,
            description TEXT,
            risk_warning TEXT DEFAULT 'Trading involves substantial risk. Past performance is not indicative of future results. NovAlgo is not responsible for any losses resulting from signals generated by this strategy.',
            webhook_token VARCHAR(100) UNIQUE NOT NULL,
            is_active BOOLEAN DEFAULT TRUE,
            total_signals INTEGER DEFAULT 0,
            last_signal_at TIMESTAMP,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    print("   ✅ Created system_strategies table")

    # User Strategy Subscriptions table
    cur.execute("""
        CREATE TABLE IF NOT EXISTS user_strategy_subscriptions (
            id SERIAL PRIMARY KEY,
            user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
            strategy_id INTEGER REFERENCES system_strategies(id) ON DELETE CASCADE,
            bot_config_id INTEGER REFERENCES user_bot_configs(id) ON DELETE CASCADE,
            is_active BOOLEAN DEFAULT TRUE,
            disclaimer_accepted_at TIMESTAMP,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(user_id, strategy_id, bot_config_id)
        )
    """)
    print("   ✅ Created user_strategy_subscriptions table")

    # User Outgoing Webhooks table
    cur.execute("""
        CREATE TABLE IF NOT EXISTS user_outgoing_webhooks (
            id SERIAL PRIMARY KEY,
            user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
            webhook_url TEXT NOT NULL,
            webhook_name VARCHAR(100),
            include_signals BOOLEAN DEFAULT TRUE,
            include_trades BOOLEAN DEFAULT TRUE,
            is_active BOOLEAN DEFAULT TRUE,
            success_count INTEGER DEFAULT 0,
            failure_count INTEGER DEFAULT 0,
            last_called_at TIMESTAMP,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(user_id, webhook_url)
        )
    """)
    print("   ✅ Created user_outgoing_webhooks table")

    # Add system_strategy_id to user_bot_configs
    cur.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'user_bot_configs' AND column_name = 'system_strategy_id'
            ) THEN
                ALTER TABLE user_bot_configs
                ADD COLUMN system_strategy_id INTEGER REFERENCES system_strategies(id) ON DELETE SET NULL;
            END IF;
        END $$
    """)
    print("   ✅ Added system_strategy_id column to user_bot_configs")

    # Create indexes
    cur.execute("CREATE INDEX IF NOT EXISTS idx_system_strategies_token ON system_strategies(webhook_token)")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_system_strategies_active ON system_strategies(is_active)")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_subscriptions_user ON user_strategy_subscriptions(user_id)")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_subscriptions_strategy ON user_strategy_subscriptions(strategy_id)")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_subscriptions_active ON user_strategy_subscriptions(is_active)")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_outgoing_webhooks_user ON user_outgoing_webhooks(user_id)")
    print("   ✅ Created indexes")


if __name__ == "__main__":
    run_migration()
