-- Migration: System Strategies and User Subscriptions
-- Description: Add tables for company TradingView strategies and user subscriptions

-- ============================================================================
-- System Strategies Table (Admin-created TradingView strategies)
-- ============================================================================
CREATE TABLE IF NOT EXISTS system_strategies (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    timeframe VARCHAR(20) NOT NULL,
    description TEXT,
    risk_warning TEXT DEFAULT 'Trading involves substantial risk. Past performance is not indicative of future results. NovAlgo is not responsible for any losses resulting from signals generated by this strategy.',
    webhook_token VARCHAR(100) UNIQUE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    total_signals INTEGER DEFAULT 0,
    last_signal_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index for webhook token lookups
CREATE INDEX IF NOT EXISTS idx_system_strategies_token ON system_strategies(webhook_token);
CREATE INDEX IF NOT EXISTS idx_system_strategies_active ON system_strategies(is_active);

-- ============================================================================
-- User Strategy Subscriptions Table
-- ============================================================================
CREATE TABLE IF NOT EXISTS user_strategy_subscriptions (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    strategy_id INTEGER REFERENCES system_strategies(id) ON DELETE CASCADE,
    bot_config_id INTEGER REFERENCES user_bot_configs(id) ON DELETE CASCADE,
    is_active BOOLEAN DEFAULT TRUE,
    disclaimer_accepted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, strategy_id, bot_config_id)
);

-- Indexes for subscription lookups
CREATE INDEX IF NOT EXISTS idx_subscriptions_user ON user_strategy_subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_strategy ON user_strategy_subscriptions(strategy_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_active ON user_strategy_subscriptions(is_active);

-- ============================================================================
-- User Outgoing Webhooks Table (for signal forwarding)
-- ============================================================================
CREATE TABLE IF NOT EXISTS user_outgoing_webhooks (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    webhook_url TEXT NOT NULL,
    webhook_name VARCHAR(100),
    include_signals BOOLEAN DEFAULT TRUE,
    include_trades BOOLEAN DEFAULT TRUE,
    is_active BOOLEAN DEFAULT TRUE,
    success_count INTEGER DEFAULT 0,
    failure_count INTEGER DEFAULT 0,
    last_called_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, webhook_url)
);

-- Index for user webhook lookups
CREATE INDEX IF NOT EXISTS idx_outgoing_webhooks_user ON user_outgoing_webhooks(user_id);

-- ============================================================================
-- Add system_strategy_id column to user_bot_configs if not exists
-- ============================================================================
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'user_bot_configs' AND column_name = 'system_strategy_id'
    ) THEN
        ALTER TABLE user_bot_configs
        ADD COLUMN system_strategy_id INTEGER REFERENCES system_strategies(id) ON DELETE SET NULL;
    END IF;
END $$;

-- ============================================================================
-- Comments
-- ============================================================================
COMMENT ON TABLE system_strategies IS 'Company TradingView strategies that users can subscribe to';
COMMENT ON TABLE user_strategy_subscriptions IS 'User subscriptions to system strategies';
COMMENT ON TABLE user_outgoing_webhooks IS 'User-configured webhooks for forwarding signals to external services';
COMMENT ON COLUMN system_strategies.webhook_token IS 'Unique token for TradingView to send signals to this strategy';
COMMENT ON COLUMN user_strategy_subscriptions.disclaimer_accepted_at IS 'Timestamp when user accepted risk disclaimer';
